In [1]:
import pandas as pd

df1 = pd.read_excel(r"C:\Users\34601\Documents\CUARTO\Trabajo Fin de Grado\glmTreat_Sano_vs_Parkinson.xlsx")
df2 = pd.read_excel(r"C:\Users\34601\Documents\CUARTO\Trabajo Fin de Grado\glmTreat_Sano_vs_ParkinsonPostDBS.xlsx")
df3 = pd.read_excel(r"C:\Users\34601\Documents\CUARTO\Trabajo Fin de Grado\glmTreat_ParkinsonPreDBS_vs_ParkinsonPostDBS.xlsx")

In [41]:
union = pd.merge(df1, df2, how = "outer", on = "Unnamed: 0")

In [42]:
union_final = pd.merge(union, df3, how = "outer", on = "Unnamed: 0")

In [43]:
union_final.head()

,Unnamed: 0,logFC_x,unshrunk.logFC_x,logCPM_x,PValue_x,FDR_x,logFC_y,unshrunk.logFC_y,logCPM_y,PValue_y,FDR_y,logFC,unshrunk.logFC,logCPM,PValue,FDR
0,RNA5S11,7.435768,7.449273,3.304783,8.320509e-15,2.376004e-10,7.373853,7.388707,3.879207,2.499793e-66,7.057665e-62,-0.279846,-0.282167,-2.067016,0.784618,0.99998
1,RNA5S10,7.954271,7.954429,10.233886,2.187895e-12,1.450646e-08,7.780000,7.780161,10.811806,1.381481e-50,1.950168e-46,-0.754959,-0.755042,4.173895,0.519730,0.99998
2,RNA5S8,7.436800,7.436898,10.407036,3.366851e-12,1.450646e-08,7.305587,7.305690,10.982595,7.113751e-45,6.694751e-41,-0.576654,-0.576692,4.856245,0.718436,0.99998
3,RNA5S9,6.997049,6.997167,9.709701,4.014595e-12,1.450646e-08,6.852049,6.852172,10.283168,1.579429e-43,8.918402e-40,-0.631934,-0.631984,4.590306,0.660903,0.99998
4,RNA5S7,7.315976,7.316065,10.424591,4.126896e-12,1.450646e-08,7.193703,7.193798,10.999459,1.129385e-43,7.971479e-40,-0.541523,-0.541555,4.992364,0.752429,0.99998

In [11]:
df1.head()

  Unnamed: 0     logFC  unshrunk.logFC     logCPM        PValue           FDR
0    RNA5S11  7.435768        7.449273   3.304783  8.320509e-15  2.376004e-10
1    RNA5S10  7.954271        7.954429  10.233886  2.187895e-12  1.450646e-08
2     RNA5S8  7.436800        7.436898  10.407036  3.366851e-12  1.450646e-08
3     RNA5S9  6.997049        6.997167   9.709701  4.014595e-12  1.450646e-08
4     RNA5S7  7.315976        7.316065  10.424591  4.126896e-12  1.450646e-08

In [12]:
df2.head()

  Unnamed: 0     logFC  unshrunk.logFC     logCPM        PValue           FDR
0    RNA5S11  7.373853        7.388707   3.879207  2.499793e-66  7.057665e-62
1    RNA5S10  7.780000        7.780161  10.811806  1.381481e-50  1.950168e-46
2     RNA5S8  7.305587        7.305690  10.982595  7.113751e-45  6.694751e-41
3     RNA5S7  7.193703        7.193798  10.999459  1.129385e-43  7.971479e-40
4     RNA5S9  6.852049        6.852172  10.283168  1.579429e-43  8.918402e-40

In [13]:
array_bool = df3["Unnamed: 0"] == "RNA5S11"

In [15]:
prueba = df3.loc[array_bool]

In [16]:
print(prueba)

      Unnamed: 0     logFC  unshrunk.logFC    logCPM    PValue      FDR
14009    RNA5S11 -0.279846       -0.282167 -2.067016  0.784618  0.99998

In [44]:
union_final = union_final.rename(columns={'Unnamed: 0': 'Genes', 
                                          'logFC_x': 'logFC_SP', 'PValue_x': 'PValue_SP',
                                          'logFC_y': 'logFC_SPost', 'PValue_y': 'PValue_SPost',
                                          'logFC': 'logFC_PrePost', 'PValue': 'PValue_PrePost'})

In [45]:
union_final.head()

,Genes,logFC_SP,unshrunk.logFC_x,logCPM_x,PValue_SP,FDR_x,logFC_SPost,unshrunk.logFC_y,logCPM_y,PValue_SPost,FDR_y,logFC_PrePost,unshrunk.logFC,logCPM,PValue_PrePost,FDR
0,RNA5S11,7.435768,7.449273,3.304783,8.320509e-15,2.376004e-10,7.373853,7.388707,3.879207,2.499793e-66,7.057665e-62,-0.279846,-0.282167,-2.067016,0.784618,0.99998
1,RNA5S10,7.954271,7.954429,10.233886,2.187895e-12,1.450646e-08,7.780000,7.780161,10.811806,1.381481e-50,1.950168e-46,-0.754959,-0.755042,4.173895,0.519730,0.99998
2,RNA5S8,7.436800,7.436898,10.407036,3.366851e-12,1.450646e-08,7.305587,7.305690,10.982595,7.113751e-45,6.694751e-41,-0.576654,-0.576692,4.856245,0.718436,0.99998
3,RNA5S9,6.997049,6.997167,9.709701,4.014595e-12,1.450646e-08,6.852049,6.852172,10.283168,1.579429e-43,8.918402e-40,-0.631934,-0.631984,4.590306,0.660903,0.99998
4,RNA5S7,7.315976,7.316065,10.424591,4.126896e-12,1.450646e-08,7.193703,7.193798,10.999459,1.129385e-43,7.971479e-40,-0.541523,-0.541555,4.992364,0.752429,0.99998

In [58]:
array_bool = union_final["Genes"] == "PAPPA"

In [59]:
busca = union_final.loc[array_bool]
busca

,Genes,logFC_SP,unshrunk.logFC_x,logCPM_x,PValue_SP,FDR_x,logFC_SPost,unshrunk.logFC_y,logCPM_y,PValue_SPost,FDR_y,logFC_PrePost,unshrunk.logFC,logCPM,PValue_PrePost,FDR
4556,PAPPA,1.443425,1.453977,-1.785657,0.22668,0.999994,0.834264,0.839536,-1.170502,0.359944,0.999984,-7.363736,-1.442695e+08,-2.30979,0.000349,0.079649

In [60]:
union_final_simplif = union_final[["Genes", "logFC_SP", "PValue_SP", "logFC_SPost", "PValue_SPost", "logFC_PrePost", "PValue_PrePost"]]

In [61]:
union_final_simplif.head()

,Genes,logFC_SP,PValue_SP,logFC_SPost,PValue_SPost,logFC_PrePost,PValue_PrePost
0,RNA5S11,7.435768,8.320509e-15,7.373853,2.499793e-66,-0.279846,0.784618
1,RNA5S10,7.954271,2.187895e-12,7.780000,1.381481e-50,-0.754959,0.519730
2,RNA5S8,7.436800,3.366851e-12,7.305587,7.113751e-45,-0.576654,0.718436
3,RNA5S9,6.997049,4.014595e-12,6.852049,1.579429e-43,-0.631934,0.660903
4,RNA5S7,7.315976,4.126896e-12,7.193703,1.129385e-43,-0.541523,0.752429

In [64]:
array_bool_simplif = union_final_simplif["Genes"] == "IGKV3D-7"

In [65]:
busca_simplif = union_final_simplif.loc[array_bool_simplif]
busca_simplif

,Genes,logFC_SP,PValue_SP,logFC_SPost,PValue_SPost,logFC_PrePost,PValue_PrePost
839,IGKV3D-7,-3.350654,0.00349,-1.618056,0.013838,2.943997,6.765488e-12

In [57]:
union_final.to_excel("union_genes_diferencial.xlsx", index = False)

In [66]:
union_final_simplif.to_excel("union_genes_diferencial_simplificado.xlsx", index = False)

In [71]:
union_final_interes = union_final_simplif.loc[(union_final_simplif["Genes"] == "IGKV3D-7") | (union_final_simplif["Genes"] == "PAPPA") | (union_final_simplif["Genes"] == "JCHAIN") | (union_final_simplif["Genes"] == "ADORA2A") | (union_final_simplif["Genes"] == "BUB1")]

In [72]:
union_final_interes

,Genes,logFC_SP,PValue_SP,logFC_SPost,PValue_SPost,logFC_PrePost,PValue_PrePost
839,IGKV3D-7,-3.350654,0.003490,-1.618056,0.013838,2.943997,6.765488e-12
1942,JCHAIN,-2.100902,0.050508,-0.194091,0.958990,3.162826,5.654616e-14
4556,PAPPA,1.443425,0.226680,0.834264,0.359944,-7.363736,3.493738e-04
7194,BUB1,-0.861235,0.379903,0.001216,0.996868,1.695617,1.859119e-02
22876,ADORA2A,-0.145143,0.913361,NaN,NaN,3.086935,6.250461e-03

In [73]:
union_final_interes.to_excel("union_genes_diferencial_interes.xlsx", index = False)